language: common-lisp
sudo: yes

env:
  matrix:
    - LISP=sbcl COVERALLS=true
    - LISP=ccl

before_install:
  # LLVM
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main'
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-get -qq update

install:
  # Install cl-travis.
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash

  # LLVM
  - sudo apt-get -qq install llvm-3.5 llvm-3.5-dev llvm-3.5-runtime libllvm3.5

before_script:
  - git clone https://github.com/fukamachi/cl-coveralls ~/lisp/cl-coveralls

script:
  - cl -l prove -l cl-coveralls
       -e '(or (coveralls:with-coveralls (:exclude (list "t"))
                 (prove:run :clwgc-test))
               (uiop:quit -1))'
